version: '3.8'
services:
  marketdata:
    image: marketdata_image:latest
    restart: unless-stopped
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  scheduler:
    image: scheduler_image:latest
    restart: unless-stopped
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
