services:
  marketdata:
    build:
      context: ./MarketData
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5001:80" 
    environment:
      - ENV=production

  scheduler:
    image: scheduler_image:latest
    restart: unless-stopped
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
